# Generated by Django 4.2.20 on 2025-05-06 15:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="code",
            field=models.CharField(
                default=api.models.generarte_unique_code, max_length=8, unique=True
            ),
        ),
    ]
